name: Flutter test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.x'
          channel: 'stable'

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: Run tests
        run: flutter test
