name: Flutter tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.x'
          channel: 'stable'

      - name: Get packages
        run: flutter pub get

      - name: Run package tests
        run: flutter test

      - name: Get example packages
        run: flutter pub get
        working-directory: ./example

      - name: Run example tests
        run: flutter test
        working-directory: ./example
